<?php
	require('sitterSessionChecker.php');
	
	//create global variables to handle database-driven select box
	$sID=0;
	$sName="";
	$pC="";
	$sType="";
	$dAvail=array();
	$price=0;
	$eDesc="";
	$pID=0;
	$date=date("Y-m-d");
	
	if(isset($_POST['submit'])){
		$feedback="";
		$success="";
		$count=0; 
		
		//create random number for the fileUpload
		$random=rand(10,100000);
		
		//get data from form fields
		$pC=$_POST['pCode'];
		$sType=$_POST['sitterType'];
		$dAvail=$_POST['dAvail'];
		$price=$_POST['price'];
		$eDesc=$_POST['eDesc'];
		
		
		/*
		TODO:
		File Upload	
		*/
		
		//validate form fields
		validate($pC, $sType, $dAvail, $price, $eDesc);
		
		//sanitize form fields
		sanitize($pC, $sType, $dAvail, $price, $eDesc);
		
		if($count==0){
			
			//insert information into database
			createPost($pC, $price, $eDesc, $date);
			
			//get the autogenerated ID of the post
			getPostID($pC, $price, $eDesc);
			
			//insert days available
			insertDays($dAvail, $pID);
			
			
			//function to save entered images
			if(count($_FILES['fileUpload']['name'])>=2){
				saveImages($pID);
			}//end if
			
			//get user ID for ternary insert
			if(isset($_SESSION['uID'])){
				$uID=$_SESSION['uID'];
			}//end of isset
			
			//insert into postcreation table
			insertTernary($pID, $sType, $uID);
			
		}//end of count-if
	}//end of isset
	
	function createPost($pC, $price, $eDesc, $date){
		//get global variables
		global $feedback;
		global $success; 
		global $count; 
		
		//make connection to database
		require('dbConnect.php');
		
		//create sql string
		if($stmt=mysqli_prepare($mysqli, 
		"INSERT INTO tblserviceposting(postCode, pricing, description, dateMade) VALUES(?, ?, ?, ?)")){
			//bind variables
			mysqli_stmt_bind_param($stmt, "siss", $pC, $price, $eDesc, $date);
			
			//execute stmt
			if(mysqli_stmt_execute($stmt)){
				return true; 
			}else{
				$feedback.="<p>Service posting not made. Please contact an administrator for assitance.</p>";
				$count++;
				return false; 
			}//end of else
			
		}//end of stmt
	}//end of createPost
	
	function escapeString($val){
		$val= filter_var($val, FILTER_SANITIZE_STRING);

		//include php code

		include('dbConnect.php');
		//sanitize data going into MySQL

		$val= mysqli_real_escape_string($mysqli, $val);
		return $val;
	}//end of function escapeString
	
	function getPostID($pC, $price, $eDesc){
		//get global variables
		global $feedback;
		global $count; 
		global $pID;
		
		//make connection to database
		require('dbConnect.php');
		
		if($stmt=mysqli_prepare($mysqli, 
		"SELECT postID FROM tblserviceposting WHERE postCode=? AND pricing=? AND description=?")){
			//bind entered parameters to mysqli statement
			 mysqli_stmt_bind_param($stmt, "sis", $pC, $price, $eDesc);
			 
			 //execute the stmt
			 mysqli_stmt_execute($stmt);
			 
			 //bind results of query
			 mysqli_stmt_bind_result($stmt, $pID);

			 //echo results of query
			 if(mysqli_stmt_fetch($stmt))
			 {	 
				  return true;
			 }else{
				 $feedback.="<p>Service posting ID not found. Please contact an administrator for assitance.</p>";
				 $count++;
				 return false;
			 }
		}//end of mysqli-if statement
	}//end of function getPostID
	
	function insertDays($dA, $pID){
		//get global variables to do stuff, I'm so tired of looking at code. 
		global $feedback; 
		global $count; 
		global $success;
		
		//find length of array
		$len=count($dA);
		
		for($i=0; $i<$len; $i++){
			
			$availability=$dA[$i];
		
		//make connection to db
		require('dbConnect.php');
		
			if($stmt=mysqli_prepare($mysqli,
			"INSERT INTO tblavailability(postID, daysAvailable) VALUES(?, ?)")){
				//bind variables
				
				mysqli_stmt_bind_param($stmt, "is", $pID, $availability);
				
				//execute stmt
				if(mysqli_stmt_execute($stmt)){
					$success.="<p>Service posting made!</p>";
				}else{
					$feedback.="<p>Availability not entered into database. Please contact an administrator for assitance.</p>";
					$count++;
				}
			}//end of if-stmt
		}//end of for loop
	}//end of function insertDays
	
	function insertTernary($pID, $sType, $uID){
		global $feedback;
		global $success;
		global $count; 
		
		//make connection to db
		require('dbConnect.php');
		
		//create sql string
		if($stmt=mysqli_prepare($mysqli, 
		"INSERT INTO tblpostcreation(serviceID, postID, userID) VALUES(?, ?, ?)")){
			//bind variables
			mysqli_stmt_bind_param($stmt, "iii", $sType, $pID, $uID);
			
			//execute stmt
			if(mysqli_stmt_execute($stmt)){
				$success.="<p>All of your details have been saved!</p>";
				return true;
			}else{
				$feedback.="<p>Your details have not been saved properly. Please contact an admin for assistance.</p>";
				$count++;
				return false; 
			}//end of if-else
		}//end of if-stmt
	}//end of function insertTernary
	
	function sanitize($pC, $sT, $dA, $p, $eD){
		//sanitize form data
		$pC= filter_var($pC, FILTER_SANITIZE_STRING);
		$sT= filter_var($sT, FILTER_SANITIZE_STRING);
		$dA= filter_var($dA, FILTER_SANITIZE_STRING);
		$p= filter_var($p, FILTER_SANITIZE_STRING);
		$eD= filter_var($eD, FILTER_SANITIZE_STRING);
		
		//include escape string function here, this uses the mysqli escape string to prevent special characters from being entered into the db
		escapeString($pC);
		escapeString($sT);
		escapeString($dA);
		escapeString($p);
		escapeString($eD);
	}//end of sanitize
	
	function saveImages($pID){
		//call global variables
		global $feedback;
		global $success;
		global $count; 
		global $random;
		
		//connect to db server and select db
		require("dbConnect.php");
		
		//code adapted from: https://www.youtube.com/watch?v=DL8LT8beVU0
		//code author: 616jk
		//accessed on: 29/03/2019
		for($i=0; $i<count($_FILES['fileUpload']['name']); $i++)
		{
			
			if((($_FILES['fileUpload']['type'][$i] == 'image/jpg')||
			($_FILES['fileUpload']['type'][$i] == 'image/jpeg')||
			($_FILES['fileUpload']['type'][$i] == 'image/pjpeg')||
			($_FILES['fileUpload']['type'][$i] == 'image/bmp')||
			($_FILES['fileUpload']['type'][$i] == 'image/png'))
			&&
			($_FILES['fileUpload']['size'][$i]<1000000))
			{
				$uploadedFile = $_FILES['fileUpload']['name'][$i]."(".$_FILES['fileUpload']['type'][$i].",".ceil($_FILES['fileUpload']['size'][$i]/1024).")Kb"."<br />";
			}
				move_uploaded_file($_FILES['fileUpload']['tmp_name'][$i],'uploads/'.$random.$_FILES['fileUpload']['name'][$i]);

			$imageName= $random.$_FILES['fileUpload']['name'][$i];
			
			//store filename in database
			if ($stmt = mysqli_prepare($mysqli,
				"INSERT INTO tblimages(imageName, postID)
				VALUES(?, ?)")){
				
				//Bind parameters to SQL Statement Object
				mysqli_stmt_bind_param($stmt, "si", $imageName, $pID);
				
				//Execute statement object and check if successful
				if(mysqli_stmt_execute($stmt)){
					$success.= "<p>Attached Images Saved Successfully!</p>";
				
				}else{
					$feedback= "<br/>Images Saved Unsuccessfully. Please contact a technician.";
					$count++;
				}//end of feedback if else 
				
			}//end mysqli prepare statement
		}//end of for loop
	}//end of functions saveImages
	
	function validate($pC, $sT, $dA, $p, $eD){
		global $feedback; 
		global $count; 
		
		//start of post code validation
		if($pC=="" || $pC==null){
			$count++;
			$feedback.="<br/> You must enter a post code!";
		}
		
		if(!ctype_alpha($pC)){
			$count++;
			$feedback.="<br/> Your post code can only contain letters!";
		}
		
		if(strlen($pC)>4){
			$count++;
			$feedback="<br/> Your post code cannot be more than 4 characters!";
		}//end of post code validation
		
		//start of sitterType validation
		if($sT=="" || $sT==null){
			$count++;
			$feedback.="<br/> You must select a sitter type!";
		}//end of sitterType validation
		
		//start of daysAvailable validation
		if(!$dA){
			$count++;
			$feedback.="<br/> You must enter the days you are available!";
		}//end of days available validation
		
		//price validation
		if($p==0 || $p==null){
			$count++;
			$feedback.="<br/> You must enter your hourly rate!";
		}
		
		if(!ctype_digit($p)){
			$count++;
			$feedback.="<br/> You must enter a digit as your rate!";
		}//end of price validation
		
		if($eD=="" || $eD==null){
			$count++;
			$feedback.="You must enter your extra details to let users know about the services you intent to provide!";
		}
		
		if(strlen($eD)>1000){
			$count++;
			$feedback.="Your description cannot be more than 1000 characters!";
		}
		
		//file validation
		
		if(count($_FILES['fileUpload']['name'])>5){
			$feedback.="<br/> You can only attach 5 images";
			$count++;
		}
		
		if(count($_FILES['fileUpload']['name'])>=2){
			//code adapted from:https://www.w3schools.com/php/php_file_upload.asp
			//accessed on: 26/03/2019
			$allowed =  array('jpeg', 'png', 'jpg', 'bmp', 'pjpeg', 'JPEG', 'PNG', 'JPG', 'BMP', 'PJPEG');
			
			for($i=0; $i<count($_FILES['fileUpload']['name']); $i++)
			{
			$path = $_FILES['fileUpload']['name'][$i];
			$ext = pathinfo($path, PATHINFO_EXTENSION);
				if(!in_array($ext,$allowed)){
					$feedback.="<br/> Image uploaded is not of type: .jpg, .jpeg, .bmp, .pjpeg or .png";
					$count++;
				}//end of if
			}//end of loop
		}//end fo else-if
	}//end of function validate
	
	
	


?>

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Urban Sitter</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/heroic-features.css" rel="stylesheet">
  
  <!--jQuery Link-->
  <script src="vendor/jquery/jquery-3.1.1.min.js"></script>
  
  <!--JavaScript Validation link-->
  <script src="js/validationJS.js"></script>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand logo" href="sitterDash.php"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
         <li class="nav-item active">
            <a class="nav-link" href="sitterDash.php">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="aboutUs.php">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contactUs.php">Contact</a>
          </li>
		   <li class="nav-item">
            <a class="nav-link" href="logout.php">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container col-sm-12">

   <!-- Header with Background Image -->
    <!-- Header with Background Image -->
    <header class="dash">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
          </div>
        </div>
      </div>
    </header>
	
	<div class="row">
	 <!-- Page Features -->
    <div class="col-sm-2">
			<div class="fluid-container">
				<table class="table">
					<tbody>
						<tr>
							<td><h6><a href="sitterDash.php">Dashboard</a></h6></td>
						</tr>

						<tr>
							<td><h6><a href="memberPost.php">Create Sitting Post</a></h6></td>
						</tr>
						
						<tr>
							<td><h6><a href="viewMemberPosts.php">View All Your Posts</a></h6></td>
						</tr>
					</tbody>
				</table>
			</div>
	</div>
	
	
	<!--Login Form-->
	<div class="container col-sm-10">
	<br/>
	<h1>Post Creation</h1>
	<div>
		<a class="BreadEff" href="sitterDash.php"> Dashboard</a> &raquo;
		<a class="BreadEff" href="memberPost.php"> Member Post</a>
	</div>
	<br/>
	<h6>You can create your own sitting posts here! Please be factual and honest with the information you provide to give everyone the right idea about who you are and the services you provide!</h6>
	<p class="emphasis">Also, please note that your contact information you provided upon sitter registration will be automatically placed onto your post.</p>
	
	
	 <?php 
			//feedback code
			global $feedback; 
			global $success;
			
	         if($feedback != ""){
		 
		     echo "<div class= 'alert alert-danger'>"; 
		       if ($count == 1) echo "<strong>$count error found.</strong>";
			   if ($count > 1) echo "<strong>$count errors found.</strong>";
		     echo "$feedback
			   </div>";
			}//end of feedback
			
			if($success != ""){
		 
		     echo "<div class= 'alert alert-success'>"; 
		     echo "$success
			   </div>";
			}//end of feedback
			/*
			//Code to check that the script is getting the right variables from form
			global $pC;
			global $sType; 
			global $dAvail;
			global $price; 
			global $eDesc;
			
			echo"$pC, $sType, $price, $eDesc";
			echo '<pre>'; print_r($dAvail); echo '</pre>'
			*/
			
	 ?>
	
	 <form name="pCreate" class="form-horizontal" method="post" action="memberPost.php" onsubmit="return postVal(this)" enctype="multipart/form-data">
	 <fieldset>
		<legend>Location and Type of Sitter:</legend>
		<!--Post code form field-->
		<div class="form-group"> 
			<label class="control-label">Post Code:</label>
		 <div class="col-sm-10">

			<input type="text" class="form-control" name="pCode" id="pCode" aria-labelledby="pCode"/> 
		 </div>
		 <span id="pcode_err"></span>
		</div>
		
		<!--Sitting Type Form Field-->
		
		<?php
		//This php script is for a database select to pull values from the tblServices table to populate a select box. 
		//call global variables
		global $sID; 
		global $sName; 
		//make connection to database
		require('dbConnect.php');
		
		//create sql string
		if($stmt=mysqli_prepare($mysqli, 
		"SELECT * FROM tblService")){
			//execute mysqli-stmt
			mysqli_stmt_execute($stmt);
			
			//bind results from stmt execution
			mysqli_stmt_bind_result($stmt, $sID, $sName);
			
			//echo start of select box
			echo"<div class='form-group'>
					<label class='control-label'>Sitting Type:</label>
					<div class='col-sm-10'>
					<select class='form-control' name='sitterType' id='sitterType' aria-labelledby='sitterType'>";
			
			//fetch results and display in selectbox
			while(mysqli_stmt_fetch($stmt)){
				//this echo contains the actual stmt records echoed out as html
				echo"
					<option value='$sID'>$sName</option>
				";//end of echo
			}//end of while
			//this echo contains the ending of the select box
			echo"<option value='' selected>---</option>
						</select>
					</div>
					<span id='sitter_err'></span>
				</div>";
		}//end of mysqli-stmt
		
		
		?>
		
	</fieldset>
	
	<fieldset>
		<legend>Day Availability and Pricing:</legend>
		<!--Availability Checkboxes-->
		<div class="form-group">
		<label class="control-label">Day Availability:</label>
		<br/>
		<div class="col-sm-10">
			<div> <label class="control-label">
				Monday:
					<input type="checkbox" name="dAvail[]" value="Monday" id="Monday" aria-labelledby="Monday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Tuesday:
					<input type="checkbox" name="dAvail[]" value="Tuesday" id="Tuesday" aria-labelledby="Tuesday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Wednesday:
					<input type="checkbox" name="dAvail[]" value="Wednesday" id="Wednesday" aria-labelledby="Wednesday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Thursday:
					<input type="checkbox" name="dAvail[]" value="Thursday" id="Thursday" aria-labelledby="Thursday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Friday:
					<input type="checkbox" name="dAvail[]" value="Friday" id="Friday" aria-labelledby="Friday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Saturday:
					<input type="checkbox" name="dAvail[]" value="Saturday" id="Saturday" aria-labelledby="Saturday"/>
				</label>
			</div>
			
			<div> <label class="control-label">
				Sunday:
					<input type="checkbox" name="dAvail" value="Sunday" id="Sunday" aria-labelledby="Sunday"/>
				</label>
			</div>
			<span id="avail_err"></span>
		</div>
		<br/>
		<!--Prices-->
		<div class="form-group">
			<div class="col-sm-10">
				<label class="form-control" for="price">Price per Hour: $
						<input type="number" name="price" id="price" value="" min="10" max="1000" aria-labelledby="price"/> per hour.
				</label>
				<span id="price_err"></span>
			</div>
		</div>
		</div>
	</fieldset>	
	
	<fieldset>
		<legend>Extra Information:</legend>
		<!--Extra Details-->
		
		<!--
			Code Adapted from: https://mdbootstrap.com/components/bootstrap-textarea/
			Code Author: mdbootstrap.com
			Code Accessed On: 01/03/2019
		-->

		<div class="form-group green-border-focus">
				<div class="col-sm-10">
					<label class="control-label">Personal Description:</label>

					<textarea class="form-control" name="eDesc"  id="eDesc" rows="3" placeholder="Enter any extra details about you or your services here!" aria-labelledby="eDesc"></textarea>
					
				</div>
				<span id="desc_err"></span>
		</div>
			
		<div class="form-group"> 
			<label class="control-label">Select Images to Upload (Optional, 2 min, 5 max):</label>
				<div class="col-sm-10">
					<!--Code Adapted from:http://www.javascripthive.info/php/php-multiple-files-upload-validation/-->
					<!--Accessed on: 26/11/2017-->
					<input type="file" class="form-control" name="fileUpload[]" id="fileUpload[]" aria-labelledby="fileUpload[]" multiple/> 
				</div>
		</div>

	</fieldset>
		 <div class="col-sm-10">
			<input type="submit" class="btn btn-primary form-control" name="submit" value="Post"/>
		</div>
	</form>
	<br/>
		
	</div>
	</div>
	
	<br/>
	<br/>
 <!-- /.row -->

 
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; UrbanSitter 2019</p>
	  <a class="text-center text-white" href="#">Privacy Policy</a>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>
